DEFAULT_TOP_K = 5
DEFAULT_EMBED_MODEL = None
DEFAULT_VECTOR_SIMILARITY_WEIGHT = 0.6

DEFAULT_SIMILARITY_THRESHOLD = 0.1
RERANK_PAGE_LIMIT = 3
RERANK_CANDIDATE_CAP = 48
RERANK_TOKEN_CAP = 256
FUSION_WEIGHT_TEXT = 0.05
FUSION_WEIGHT_VECTOR = 0.95
DENSE_SIMILARITY_FALLBACK = 0.17
DEFAULT_USE_MODEL_RERANK = True
DEFAULT_USE_INTENT_BONUS = True

# Retrieval runtime scoring knobs (must stay configurable)
RUNTIME_SCORE_TITLE_HARD_BONUS = 8
RUNTIME_SCORE_TITLE_MISS_PENALTY = 6
RUNTIME_SCORE_MUST_INCLUDE_PER_MATCH = 3
RUNTIME_SCORE_MUST_INCLUDE_FULL_COVERAGE_BONUS = 5
RUNTIME_SCORE_MUST_NOT_INCLUDE_HARD_PENALTY = 12
RUNTIME_SCORE_DOC_TYPE_PREFER_BONUS = 3
RUNTIME_SCORE_DOC_TYPE_AVOID_PENALTY = 4
RUNTIME_SCORE_LEGAL_METADATA_UNIT = 1
RUNTIME_SCORE_LEGAL_METADATA_STRONG_BONUS = 10

DEFAULT_CHUNK_TOKEN_NUM = 128
DEFAULT_CHUNK_DELIMITER = "\n!?。；！？"
DEFAULT_LAYOUT_RECOGNIZE = "DeepDOC"
PDF_PLAIN_TEXT_SIZE_THRESHOLD_BYTES = 5 * 1024 * 1024
